### PR TITLE
Add id and name settings to all input elements

### PR DESCRIPTION
**Pull request by jiji262**
Note: now the id and name will be set the same value.

### CODE REVIEW

**Comment by craighooghiem** [comment]
It looks reasonable to me. However, the whole thing is being rebuilt right now and possibly being ported to backbone.
I've asked him to look at adding name and ID fields as this is an oversight for a form generator.

For my personal build I basically did what you did.

**Comment by minikomi** [comment]
Thanks for the commit!
Yes, I'm rewriting this, but I will be happy to merge anything which improves the current version.

It's quite hard to see what changed if the entire file is replaced.. Is it possible to make a commit with only the parts you added?

**Comment by minikomi** [comment]
Also some other things which need fixing before I pull:
- having an id set by default to eg. "text" means that you will have overlapping id's if you don't set them.
- The form in the popover isn't being populated by the id / name if it is set 
  - i.e. set an id -> save -> click again to set id & it's blank.
- mixed tabs & spaces
- some formatting issues but not too important - I can reformat later

**Comment by jiji262** [comment]
## The following problems has been fixed, I will pull later.

having an id set by default to eg. "text" means that you will have overlapping id's if you don't set them.
The form in the popover isn't being populated by the id / name if it is set i.e. set an id -> save -> click again to set id & it's blank.
mixed tabs & spaces

**Comment by minikomi** [comment]
- spaces & tabs.. and 
- git config core.autocrlf = true (It's really hard to see what you committed the first time because windows added a lot of ^M's to every line)
- If the id/name `$(e).val()` is set to "", we need to `$(value).removeAttr("id").removeAttr("name")`

**Comment by minikomi** [comment]
This is included as part of rewriting the tool using bootstrap.

**Comment by mustafauysal** [comment]
automatic id would be handy

**Pull request closed without merging**
